//
// API ENDPOINTS USER
//

// funkar - HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// funkar - HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "65c4e5991043f0e4b59faec0"
}

###

// funkar - SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Alla Testsson",
  "email": "test@mail.com",
  "password": "test"
}

###

// funkar - LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "lisa@mail.com",
  "password": "test"
} 

###

//
// API ENDPOINTS PRODUKTER
//

// funkar - HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// funkar - HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/65c4e48f1043f0e4b59faebc

###

// funkar - SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 11",
  "description": "Beskrivning av produkt 1",
  "price": 100, 
  "lager": 1000
}

###

//
// API ENDPOINTS ORDERS
//

// funkar - SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "65c4e57f1043f0e4b59faebf",
      "products": [
    {
      "productId": "65c106a95e8eec5ed3df6f9b",
      "quantity": 100
    },
    {
      "productId": "65c13c304851e787c0081636",
      "quantity": 4
    }
  ]
}

###


// funkar - HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###